# src/graph/state.py
from typing import TypedDict, Annotated, List, Optional, Dict, Any
from langchain_core.messages import BaseMessage
import operator

class GraphState(TypedDict):
    """
    Represents the state of our graph.

    Attributes:
        messages: A list of messages that form the conversation.
        next_specialist: The name of the specialist to route to next.
        text_to_process: Text that a specialist may need to process.
        extracted_data: The structured data extracted by the data extractor.
        error: An error message, if any.
        json_artifact: A JSON object (dict) artifact generated by a specialist.
        html_artifact: An HTML string artifact generated by a specialist.
        system_plan: A structured plan generated by a specialist.
        turn_count: A counter to prevent infinite loops.
        suggested_next_specialist: A hint from a specialist for the next step.
        task_is_complete: A flag to signal that the workflow's goal has been met.
    """
    messages: Annotated[List[BaseMessage], operator.add]
    next_specialist: Optional[str]
    text_to_process: Optional[str]
    extracted_data: Optional[Dict[str, Any]]
    error: Optional[str]
    json_artifact: Optional[Dict[str, Any]]
    html_artifact: Optional[str]
    system_plan: Optional[Dict[str, Any]]
    turn_count: int
    suggested_next_specialist: Optional[str]
    task_is_complete: bool
