# app/src/specialists/schemas/_state.py
from pydantic import BaseModel, Field
from typing import List, Optional, Literal

class Scratchpad(BaseModel):
    """
    A model for the 'scratchpad', a transient, in-memory dictionary for passing
    data between specialists within a single workflow run.
    """
    user_response_snippets: List[str] = Field(
        default_factory=list,
        description="A list of user-facing text snippets generated by specialists."
    )
    critique_decision: Optional[Literal["ACCEPT", "REVISE"]] = Field(
        default=None,
        description="The machine-readable decision from the CriticSpecialist."
    )
    termination_reason: Optional[str] = Field(
        default=None,
        description="The reason for workflow termination, e.g., from loop detection."
    )